### ISSUE TITLE
Rename zstat references to contrast names?

### ISSUE THREAD

**Issue by wasciutto** [UNCDEPENdLab/fmri.pipeline#3]
It's always bugged me that fsl by default names its files like `zstat[index]` instead of using the actual name of the contrast, forcing the user to pull up a reference of which zstat index goes with each contrast when glancing through fsl's output:

![image](https://user-images.githubusercontent.com/34407871/233683592-893376cf-3cb7-4806-96b9-050e742567e1.png)
![image](https://user-images.githubusercontent.com/34407871/233683658-d20aa10c-e6f1-48f7-824f-788f04614adc.png)
![image](https://user-images.githubusercontent.com/34407871/233683712-51b3fadb-bc61-4502-b8f1-b7df41dc19f9.png)

If it's possible to change this within the fsf files (not sure), we could take advantage of our opportunity to name these files according to contrast, for example:

![image](https://user-images.githubusercontent.com/34407871/233685104-c3042c7f-4af4-47fc-a5f9-9f120cec62b2.png)

Of course, there may be a good reason for using zstat[index] that I am not aware of - maybe zstat is meant to represent a more generic example that just contrast, for example. Also, again may not be possible due to it being non-configurable in the template files.

**Comment by wasciutto** [comment]
Update: noticed that L3 names its files as requested here for L1

**Comment by michaelhallquist** [comment]
Thanks, Will. The problem you name bugs me as well. Overall, I don't think it's a good idea to alter the names of FSL outputs since downstream programs (including some within FSL) make assumptions about the structure.

I wrote the `combine_feat_l3_to_afni` with this problem in mind. That function gives the user substantial flexibility in how FEAT group outputs are structured, assembling them into BRIK/HEAD files that can be loaded into AFNI, which I think does a better job of helping the user flip through and compare many maps.

Perhaps we could think of a similar extension on the FSL side (e.g., structuring custom folder outputs). Open to input on this.

**Comment by wasciutto** [comment]
Closing due to Michael's feedback above
